// <auto-generated />
using ApiHospital;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiHospital.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220919234838_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiHospital.Controllers.Entidades.Hospital", b =>
                {
                    b.Property<int>("IdHospital")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHospital"), 1L, 1);

                    b.Property<string>("NombreHospital")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHospital");

                    b.ToTable("Hospitales");
                });

            modelBuilder.Entity("ApiHospital.Controllers.Entidades.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"), 1L, 1);

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("estatura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("peso")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPaciente");

                    b.HasIndex("HospitalId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ApiHospital.Controllers.Entidades.Paciente", b =>
                {
                    b.HasOne("ApiHospital.Controllers.Entidades.Hospital", null)
                        .WithMany("Pacientes")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiHospital.Controllers.Entidades.Hospital", b =>
                {
                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
